// src/components/ScannerWrapper.jsx

import React from 'react';
import { Box } from '@mui/material';

/**
 * This wrapper component applies custom styles to the child elements
 * generated by the html5-qrcode library to make them match the MUI theme.
 */
const ScannerWrapper = ({ children }) => {
  return (
    <Box
      sx={{
        width: '100%',
        position: 'relative',
        
        // Target the main container div created by the library
        '& #html5qr-code-full-region': {
          background: 'transparent',
        },

        // Target the border div around the video feed
        '& #html5qr-code-full-region_border': {
          border: 'none', // Remove the library's default border
        },
        
        // Style the video element itself
        '& video': {
          width: '100% !important',
          height: 'auto !important',
          borderRadius: '8px', // Match MUI's border radius
        },
        
        // Hide the "Scan an image file" link and the horizontal line below it
        '& #html5-qrcode-anchor-scan-type-change, & #html5-qrcode-anchor-scan-type-change + hr': {
          display: 'none',
        },

        // Style the camera selection dropdown to match the dark theme
        '& #html5qr-code-full-region_select_camera': {
          display: 'block',
          width: '100%',
          backgroundColor: 'rgba(255, 255, 255, 0.1)',
          color: '#fff',
          border: '1px solid rgba(255, 255, 255, 0.2)',
          borderRadius: '4px',
          padding: '10px',
          marginTop: '16px',
          '&:focus': {
            outline: 'none',
            borderColor: 'primary.main',
          },
        },
      }}
    >
      {children}
    </Box>
  );
};

export default ScannerWrapper;